name: PunkModBot PR Review

on:
  # Toutes les 5 minutes
  schedule:
    - cron: '*/5 * * * *'

  # Ou manuellement
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Call PunkModBot
        run: |
          response=$(curl -s https://madebypunks.co/api/mod)
          echo "$response"

          reviewed=$(echo "$response" | jq -r '.reviewed | length')
          echo "Reviewed $reviewed PRs"
